import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = join(__dirname, '..', 'src', 'data', 'vocabulary', 'HSK 5.json');

const URLs = [
  'https://raw.githubusercontent.com/chinese-learning-tools/hsk/master/HSK5.txt',
  'https://raw.githubusercontent.com/ArnaudBrousseau/HSK-5-Vocabulary/main/HSK5.txt',
  'https://raw.githubusercontent.com/bluejames2000/hsk-vocabulary/master/HSK5.txt',
  'https://raw.githubusercontent.com/clembench/HSK/master/HSK5.txt',
];

// Fallback list of 100 words covering common HSK 5 topics
const FALLBACK_WORDS = [
  ["爱惜","ài xī","to cherish"],
  ["安排","ān pái","to arrange"],
  ["安全","ān quán","safe"],
  ["按时","àn shí","on time"],
  ["把握","bǎ wò","to grasp"],
  ["摆脱","bǎi tuō","to get rid of"],
  ["办理","bàn lǐ","to handle"],
  ["包括","bāo kuò","to include"],
  ["保持","bǎo chí","to maintain"],
  ["保护","bǎo hù","to protect"],
  ["保证","bǎo zhèng","to guarantee"],
  ["抱歉","bào qiàn","sorry"],
  ["报道","bào dào","to report"],
  ["悲观","bēi guān","pessimistic"],
  ["必然","bì rán","inevitable"],
  ["必须","bì xū","must"],
  ["编辑","biān jí","to edit"],
  ["辩论","biàn lùn","to debate"],
  ["标志","biāo zhì","symbol"],
  ["博物馆","bó wù guǎn","museum"],
  ["补偿","bǔ cháng","to compensate"],
  ["不必","bú bì","need not"],
  ["不断","bú duàn","continuously"],
  ["不过","bú guò","however"],
  ["不禁","bù jīn","can't help"],
  ["不满","bù mǎn","dissatisfied"],
  ["不然","bù rán","otherwise"],
  ["不足","bù zú","insufficient"],
  ["采访","cǎi fǎng","to interview"],
  ["采取","cǎi qǔ","to adopt"],
  ["参观","cān guān","to visit"],
  ["参加","cān jiā","to participate"],
  ["残酷","cán kù","cruel"],
  ["灿烂","càn làn","brilliant"],
  ["差别","chā bié","difference"],
  ["产量","chǎn liàng","output"],
  ["长期","cháng qī","long-term"],
  ["超过","chāo guò","to exceed"],
  ["吵架","chǎo jià","to quarrel"],
  ["彻底","chè dǐ","thoroughly"],
  ["沉默","chén mò","silent"],
  ["沉重","chén zhòng","heavy (heart)"],
  ["称呼","chēng hū","to call"],
  ["成就","chéng jiù","achievement"],
  ["成立","chéng lì","to establish"],
  ["成熟","chéng shú","ripe / mature"],
  ["承担","chéng dān","to undertake"],
  ["承认","chéng rèn","to admit"],
  ["吃饭","chī fàn","to eat"],
  ["充分","chōng fèn","sufficient"],
  ["充满","chōng mǎn","to fill"],
  ["重复","chóng fù","to repeat"],
  ["重新","chóng xīn","anew"],
  ["出发","chū fā","to depart"],
  ["出路","chū lù","way out"],
  ["出现","chū xiàn","to appear"],
  ["厨房","chú fáng","kitchen"],
  ["处理","chǔ lǐ","to handle"],
  ["传播","chuán bō","to spread"],
  ["创造","chuàng zào","to create"],
  ["吹牛","chuī niú","to brag"],
  ["辞职","cí zhí","to resign"],
  ["此外","cǐ wài","besides"],
  ["刺激","cì jī","to stimulate"],
  ["聪明","cōng míng","clever"],
  ["从事","cóng shì","to engage in"],
  ["促进","cù jìn","to promote"],
  ["措施","cuò shī","measure"],
  ["答应","dā yìng","to promise"],
  ["达到","dá dào","to achieve"],
  ["打败","dǎ bài","to defeat"],
  ["打扮","dǎ bàn","to dress up"],
  ["打击","dǎ jī","to strike"],
  ["打招呼","dǎ zhāo hū","to greet"],
  ["大胆","dà dǎn","bold"],
  ["大概","dà gài","roughly"],
  ["大家","dà jiā","everyone"],
  ["大量","dà liàng","large amount"],
  ["大陆","dà lù","continent"],
  ["大使馆","dà shǐ guǎn","embassy"],
  ["大约","dà yuē","approximately"],
  ["代表","dài biǎo","to represent"],
  ["代替","dài tì","to replace"],
  ["担任","dān rèn","to hold (a position)"],
  ["担心","dān xīn","to worry"],
  ["单纯","dān chún","simple"],
  ["单调","dān diào","monotonous"],
  ["单位","dān wèi","unit"],
  ["当然","dāng rán","of course"],
  ["当时","dāng shí","at that time"],
  ["导致","dǎo zhì","to lead to"],
  ["到处","dào chù","everywhere"],
  ["到底","dào dǐ","after all"],
  ["道德","dào dé","morality"],
  ["得到","dé dào","to get"],
  ["登记","dēng jì","to register"],
  ["等待","děng dài","to wait"],
  ["等于","děng yú","to equal"],
  ["敌人","dí rén","enemy"],
  ["底下","dǐ xià","underneath"],
  ["地道","dì dào","genuine"],
  ["地点","dì diǎn","location"],
  ["地球","dì qiú","earth"],
  ["地址","dì zhǐ","address"],
  ["典型","diǎn xíng","typical"],
  ["点心","diǎn xīn","snack"],
  ["电视台","diàn shì tái","TV station"],
  ["调查","diào chá","to investigate"],
  ["调动","diào dòng","to transfer"],
  ["东北","dōng běi","northeast"],
  ["冬季","dōng jì","winter"],
  ["动身","dòng shēn","to set out"],
  ["动手","dòng shǒu","to start work"],
  ["独立","dú lì","independent"],
  ["度过","dù guò","to spend (time)"],
  ["对待","duì dài","to treat"],
  ["对方","duì fāng","the other party"],
  ["对付","duì fu","to deal with"],
  ["对比","duì bǐ","comparison"],
  ["对话","duì huà","dialogue"],
  ["对得起","duì de qǐ","to be worthy of"],
  ["多么","duō me","how (intensifier)"],
  ["恶意","è yì","malice"],
  ["儿童","ér tóng","child"],
  ["发表","fā biǎo","to publish"],
  ["发达","fā dá","developed"],
  ["发动","fā dòng","to launch"],
  ["发抖","fā dǒu","to shiver"],
  ["发挥","fā huī","to bring into play"],
  ["发明","fā míng","invention"],
  ["发生","fā shēng","to happen"],
  ["发现","fā xiàn","to discover"],
  ["发展","fā zhǎn","to develop"],
  ["罚款","fá kuǎn","fine (penalty)"],
  ["法律","fǎ lǜ","law"],
  ["凡是","fán shì","every"],
  ["繁荣","fán róng","prosperous"],
  ["反对","fǎn duì","to oppose"],
  ["反复","fǎn fù","repeatedly"],
  ["反应","fǎn yìng","reaction"],
  ["反映","fǎn yìng","to reflect"],
  ["反正","fǎn zhèng","anyway"],
  ["范围","fàn wéi","scope"],
  ["方案","fāng àn","plan"],
  ["方便","fāng biàn","convenient"],
  ["方面","fāng miàn","aspect"],
  ["方式","fāng shì","way"],
  ["防止","fáng zhǐ","to prevent"],
  ["访问","fǎng wèn","to visit"],
  ["放弃","fàng qì","to give up"],
  ["放松","fàng sōng","to relax"],
  ["飞行","fēi xíng","flight"],
  ["非常","fēi cháng","very"],
  ["费用","fèi yòng","cost"],
  ["分别","fēn bié","to part"],
  ["分配","fēn pèi","to distribute"],
  ["分析","fēn xī","to analyze"],
  ["奋斗","fèn dòu","to strive"],
  ["风格","fēng gé","style"],
  ["风景","fēng jǐng","scenery"],
  ["否定","fǒu dìng","to negate"],
  ["否则","fǒu zé","otherwise"],
  ["符合","fú hé","to conform"],
  ["服务","fú wù","to serve"],
  ["负担","fù dān","burden"],
  ["负责","fù zé","to be responsible"],
  ["改变","gǎi biàn","to change"],
  ["改革","gǎi gé","to reform"],
  ["改进","gǎi jìn","to improve"],
  ["改善","gǎi shàn","to improve"],
  ["改造","gǎi zào","to transform"],
  ["改正","gǎi zhèng","to correct"],
  ["干部","gàn bù","cadre"],
  ["刚才","gāng cái","just now"],
  ["高度","gāo dù","height"],
  ["告别","gào bié","to say goodbye"],
  ["告诉","gào su","to tell"],
  ["歌唱","gē chàng","to sing"],
  ["个别","gè bié","individual"],
  ["个人","gè rén","individual"],
  ["各个","gè gè","each"],
  ["根本","gēn běn","fundamental"],
  ["更加","gèng jiā","even more"],
  ["工厂","gōng chǎng","factory"],
  ["工程","gōng chéng","engineering"],
  ["工会","gōng huì","labor union"],
  ["工具","gōng jù","tool"],
  ["工人","gōng rén","worker"],
  ["工业","gōng yè","industry"],
  ["工资","gōng zī","wages"],
  ["工作","gōng zuò","work"],
  ["公共","gōng gòng","public"],
  ["公交","gōng jiāo","public transport"],
  ["公司","gōng sī","company"],
  ["公正","gōng zhèng","just"],
  ["巩固","gǒng gù","to consolidate"],
  ["贡献","gòng xiàn","contribution"],
  ["沟通","gōu tōng","to communicate"],
  ["构成","gòu chéng","to constitute"],
  ["估计","gū jì","to estimate"],
  ["鼓励","gǔ lì","to encourage"],
  ["古代","gǔ dài","ancient times"],
  ["顾客","gù kè","customer"],
  ["故意","gù yì","on purpose"],
  ["关心","guān xīn","to care about"],
  ["关于","guān yú","about"],
  ["观察","guān chá","to observe"],
  ["观点","guān diǎn","viewpoint"],
  ["管理","guǎn lǐ","to manage"],
  ["冠军","guàn jūn","champion"],
  ["光明","guāng míng","bright"],
  ["广大","guǎng dà","vast"],
  ["广泛","guǎng fàn","wide-ranging"],
  ["规律","guī lǜ","rule"],
  ["规模","guī mó","scale"],
  ["规则","guī zé","rule"],
  ["国家","guó jiā","country"],
  ["果然","guǒ rán","indeed"],
  ["过程","guò chéng","process"],
  ["过去","guò qù","past"],
  ["害羞","hài xiū","shy"],
  ["害怕","hài pà","to fear"],
  ["行业","háng yè","industry"],
  ["好处","hǎo chù","benefit"],
  ["好好","hǎo hǎo","properly"],
  ["好像","hǎo xiàng","as if"],
  ["号召","hào zhào","to call for"],
  ["合格","hé gé","qualified"],
  ["合理","hé lǐ","reasonable"],
  ["合适","hé shì","suitable"],
  ["合作","hé zuò","to cooperate"],
  ["和平","hé píng","peace"],
  ["核心","hé xīn","core"],
  ["黑暗","hēi àn","dark"],
  ["后果","hòu guǒ","consequence"],
  ["后悔","hòu huǐ","to regret"],
  ["后来","hòu lái","afterwards"],
  ["忽然","hū rán","suddenly"],
  ["忽视","hū shì","to ignore"],
  ["护照","hù zhào","passport"],
  ["花园","huā yuán","garden"],
  ["化学","huà xué","chemistry"],
  ["话题","huà tí","topic"],
  ["怀念","huái niàn","to cherish memory"],
  ["怀疑","huái yí","to doubt"],
  ["环境","huán jìng","environment"],
  ["欢迎","huān yíng","to welcome"],
  ["换人","huàn rén","to substitute"],
  ["恢复","huī fù","to recover"],
  ["回忆","huí yì","to recall"],
  ["汇报","huì bào","to report"],
  ["会议","huì yì","meeting"],
  ["婚姻","hūn yīn","marriage"],
  ["活跃","huó yuè","active"],
  ["火柴","huǒ chái","match"],
  ["伙伴","huǒ bàn","partner"],
  ["或许","huò xǔ","perhaps"],
  ["基础","jī chǔ","foundation"],
  ["机场","jī chǎng","airport"],
  ["激动","jī dòng","excited"],
  ["积极","jī jí","positive"],
  ["积累","jī lěi","to accumulate"],
  ["基本上","jī běn shàng","basically"],
  ["激烈","jī liè","fierce"],
  ["集市","jí shì","market"],
  ["集体","jí tǐ","collective"],
  ["集中","jí zhōng","to concentrate"],
  ["计算","jì suàn","to calculate"],
  ["技术","jì shù","technology"],
  ["纪念","jì niàn","to commemorate"],
  ["纪律","jì lǜ","discipline"],
  ["继续","jì xù","to continue"],
  ["纪录","jì lù","record"],
  ["季节","jì jié","season"],
  ["减少","jiǎn shǎo","to reduce"],
  ["检查","jiǎn chá","to inspect"],
  ["简单","jiǎn dān","simple"],
  ["建立","jiàn lì","to establish"],
  ["建设","jiàn shè","to build"],
  ["建议","jiàn yì","to suggest"],
  ["建筑","jiàn zhù","building"],
  ["健康","jiàn kāng","health"],
  ["将来","jiāng lái","future"],
  ["讲解","jiǎng jiě","to explain"],
  ["奖金","jiǎng jīn","bonus"],
  ["降低","jiàng dī","to lower"],
  ["交流","jiāo liú","to exchange"],
  ["交通","jiāo tōng","traffic"],
  ["骄傲","jiāo ào","proud"],
  ["教材","jiào cái","teaching material"],
  ["教练","jiào liàn","coach"],
  ["教训","jiào xun","lesson"],
  ["教育","jiào yù","education"],
  ["阶段","jiē duàn","stage"],
  ["结果","jié guǒ","result"],
  ["结合","jié hé","to combine"],
  ["节约","jié yuē","to save"],
  ["解放","jiě fàng","to liberate"],
  ["解决","jiě jué","to solve"],
  ["解释","jiě shì","to explain"],
  ["借书","jiè shū","to borrow a book"],
  ["今后","jīn hòu","from now on"],
  ["紧张","jǐn zhāng","nervous"],
  ["进步","jìn bù","progress"],
  ["进口","jìn kǒu","import"],
  ["进入","jìn rù","to enter"],
  ["进行","jìn xíng","to proceed"],
  ["禁止","jìn zhǐ","to forbid"],
  ["经常","jīng cháng","often"],
  ["经过","jīng guò","to pass through"],
  ["经济","jīng jì","economy"],
  ["经历","jīng lì","experience"],
  ["经验","jīng yàn","experience"],
  ["经营","jīng yíng","to manage"],
  ["警察","jǐng chá","police"],
  ["竞争","jìng zhēng","competition"],
  ["究竟","jiū jìng","after all"],
  ["就职","jiù zhí","to take office"],
  ["举办","jǔ bàn","to hold (event)"],
  ["举行","jǔ xíng","to hold (meeting)"],
  ["具体","jù tǐ","concrete"],
  ["巨大","jù dà","huge"],
  ["具备","jù bèi","to possess"],
  ["捐款","juān kuǎn","to donate"],
  ["决定","jué dìng","to decide"],
  ["决心","jué xīn","determination"],
  ["绝对","jué duì","absolute"],
  ["军队","jūn duì","army"],
  ["开发","kāi fā","to develop"],
  ["开放","kāi fàng","to open up"],
  ["开始","kāi shǐ","to start"],
  ["开展","kāi zhǎn","to launch"],
  ["看法","kàn fǎ","opinion"],
  ["考虑","kǎo lǜ","to consider"],
  ["考试","kǎo shì","exam"],
  ["科学","kē xué","science"],
  ["可爱","kě ài","cute"],
  ["可怜","kě lián","pitiful"],
  ["可能","kě néng","possible"],
  ["可是","kě shì","but"],
  ["可惜","kě xī","unfortunate"],
  ["客人","kè rén","guest"],
  ["课程","kè chéng","course"],
  ["空间","kōng jiān","space"],
  ["空气","kōng qì","air"],
  ["恐怕","kǒng pà","I'm afraid"],
  ["控制","kòng zhì","to control"],
  ["哭泣","kū qì","to cry"],
  ["苦闷","kǔ mèn","depressed"],
  ["夸奖","kuā jiǎng","to praise"],
  ["快乐","kuài lè","happy"],
  ["宽敞","kuān chang","spacious"],
  ["困难","kùn nan","difficult"],
  ["扩大","kuò dà","to expand"],
  ["垃圾","lā jī","garbage"],
  ["来不及","lái bu jí","too late"],
  ["浪费","làng fèi","to waste"],
  ["劳动","láo dòng","labor"],
  ["老师","lǎo shī","teacher"],
  ["乐观","lè guān","optimistic"],
  ["类似","lèi sì","similar"],
  ["冷静","lěng jìng","calm"],
  ["离开","lí kāi","to leave"],
  ["理解","lǐ jiě","to understand"],
  ["理论","lǐ lùn","theory"],
  ["理想","lǐ xiǎng","ideal"],
  ["力量","lì liàng","strength"],
  ["联系","lián xì","to contact"],
  ["连续","lián xù","continuous"],
  ["恋爱","liàn ài","to be in love"],
  ["良好","liáng hǎo","good"],
  ["谅解","liàng jiě","to understand"],
  ["了不起","liǎo bu qǐ","amazing"],
  ["邻居","lín jū","neighbor"],
  ["临时","lín shí","temporary"],
  ["灵活","líng huó","flexible"],
  ["领导","lǐng dǎo","to lead"],
  ["流水","liú shuǐ","flowing water"],
  ["流行","liú xíng","popular"],
  ["留学","liú xué","to study abroad"],
  ["落后","luò hòu","to fall behind"],
  ["麻烦","má fan","troublesome"],
  ["马上","mǎ shàng","immediately"],
  ["满意","mǎn yì","satisfied"],
  ["矛盾","máo dùn","contradiction"],
  ["贸易","mào yì","trade"],
  ["没有","méi yǒu","without"],
  ["美味","měi wèi","delicious"],
  ["梦想","mèng xiǎng","dream"],
  ["秘密","mì mì","secret"],
  ["面对","miàn duì","to face"],
  ["面积","miàn jī","area"],
  ["面临","miàn lín","to confront"],
  ["面貌","miàn mào","appearance"],
  ["描述","miáo shù","to describe"],
  ["描写","miáo xiě","to depict"],
  ["秒针","miǎo zhēn","second hand"],
  ["民族","mín zú","ethnic group"],
  ["命令","mìng lìng","command"],
  ["命运","mìng yùn","fate"],
  ["模仿","mó fǎng","to imitate"],
  ["模糊","mó hu","blurry"],
  ["模式","mó shì","model"],
  ["陌生","mò shēng","strange"],
  ["目标","mù biāo","goal"],
  ["目前","mù qián","currently"],
  ["目光","mù guāng","gaze"],
  ["耐心","nài xīn","patient"],
  ["难道","nán dào","could it be"],
  ["难受","nán shòu","uncomfortable"],
  ["内心","nèi xīn","inner heart"],
  ["能力","néng lì","ability"],
  ["年龄","nián líng","age"],
  ["宁可","nìng kě","would rather"],
  ["农民","nóng mín","farmer"],
  ["努力","nǔ lì","hardworking"],
  ["暖和","nuǎn huo","warm"],
  ["偶尔","ǒu ěr","occasionally"],
  ["爬山","pá shān","mountain climbing"],
  ["排除","pái chú","to eliminate"],
  ["判断","pàn duàn","to judge"],
  ["培训","péi xùn","training"],
  ["赔偿","péi cháng","compensation"],
  ["佩服","pèi fu","to admire"],
  ["批评","pī píng","to criticize"],
  ["批准","pī zhǔn","to approve"],
  ["疲劳","pí láo","tired"],
  ["片面","piàn miàn","one-sided"],
  ["漂亮","piào liang","beautiful"],
  ["平时","píng shí","usually"],
  ["评价","píng jià","to evaluate"],
  ["评论","píng lùn","comment"],
  ["普遍","pǔ biàn","universal"],
  ["普通","pǔ tōng","ordinary"],
  ["期待","qī dài","to expect"],
  ["期间","qī jiān","period"],
  ["其实","qí shí","actually"],
  ["其他","qí tā","other"],
  ["企业","qǐ yè","enterprise"],
  ["启发","qǐ fā","to inspire"],
  ["气氛","qì fēn","atmosphere"],
  ["气候","qì hòu","climate"],
  ["千万","qiān wàn","ten million"],
  ["前景","qián jǐng","prospect"],
  ["前途","qián tú","future"],
  ["强调","qiáng diào","to emphasize"],
  ["强度","qiáng dù","intensity"],
  ["强有力","qiáng yǒu lì","powerful"],
  ["亲切","qīn qiè","kind"],
  ["亲自","qīn zì","personally"],
  ["勤奋","qín fèn","diligent"],
  ["青春","qīng chūn","youth"],
  ["轻松","qīng sōng","relaxed"],
  ["清理","qīng lǐ","to clean up"],
  ["情况","qíng kuàng","situation"],
  ["情绪","qíng xù","mood"],
  ["请求","qǐng qiú","request"],
  ["庆祝","qìng zhù","to celebrate"],
  ["区别","qū bié","difference"],
  ["趋势","qū shì","trend"],
  ["取消","qǔ xiāo","to cancel"],
  ["全面","quán miàn","comprehensive"],
  ["缺点","quē diǎn","shortcoming"],
  ["确保","què bǎo","to ensure"],
  ["然后","rán hòu","then"],
  ["燃烧","rán shāo","to burn"],
  ["热爱","rè ài","to love deeply"],
  ["热烈","rè liè","warm (reception)"],
  ["人才","rén cái","talent"],
  ["人工","rén gōng","artificial"],
  ["人口","rén kǒu","population"],
  ["人类","rén lèi","humanity"],
  ["人民","rén mín","people"],
  ["任何","rèn hé","any"],
  ["任务","rèn wu","task"],
  ["认识","rèn shi","to know"],
  ["认为","rèn wéi","to think"],
  ["认真","rèn zhēn","serious"],
  ["仍然","réng rán","still"],
  ["日常","rì cháng","daily"],
  ["日程","rì chéng","schedule"],
  ["容纳","róng nà","to accommodate"],
  ["容易","róng yì","easy"],
  ["如果","rú guǒ","if"],
  ["软件","ruǎn jiàn","software"],
  ["森林","sēn lín","forest"],
  ["沙漠","shā mò","desert"],
  ["沙滩","shā tān","beach"],
  ["善良","shàn liáng","kind"],
  ["商业","shāng yè","business"],
  ["上班","shàng bān","to go to work"],
  ["少年","shào nián","teenager"],
  ["设计","shè jì","to design"],
  ["设立","shè lì","to set up"],
  ["社会","shè huì","society"],
  ["社区","shè qū","community"],
  ["申请","shēn qǐng","to apply"],
  ["深刻","shēn kè","profound"],
  ["什么","shén me","what"],
  ["甚至","shèn zhì","even"],
  ["生产","shēng chǎn","to produce"],
  ["生动","shēng dòng","vivid"],
  ["生活","shēng huó","life"],
  ["生命","shēng mìng","life"],
  ["生物","shēng wù","organism"],
  ["生长","shēng zhǎng","to grow"],
  ["省得","shěng de","so as to avoid"],
  ["胜利","shèng lì","victory"],
  ["失败","shī bài","failure"],
  ["失望","shī wàng","disappointed"],
  ["十分","shí fēn","very"],
  ["时代","shí dài","era"],
  ["时候","shí hou","time"],
  ["时间","shí jiān","time"],
  ["时期","shí qī","period"],
  ["实际","shí jì","actual"],
  ["实践","shí jiàn","practice"],
  ["实现","shí xiàn","to realize"],
  ["实行","shí xíng","to implement"],
  ["实验","shí yàn","experiment"],
  ["食物","shí wù","food"],
  ["使用","shǐ yòng","to use"],
  ["始终","shǐ zhōng","from start to finish"],
  ["事业","shì yè","cause"],
  ["事实","shì shí","fact"],
  ["事务","shì wù","affairs"],
  ["事先","shì xiān","beforehand"],
  ["试卷","shì juàn","exam paper"],
  ["收获","shōu huò","harvest"],
  ["收入","shōu rù","income"],
  ["收拾","shōu shi","to tidy up"],
  ["手续","shǒu xù","procedure"],
  ["手机","shǒu jī","mobile phone"],
  ["首先","shǒu xiān","firstly"],
  ["受到","shòu dào","to receive"],
  ["书店","shū diàn","bookstore"],
  ["舒服","shū fu","comfortable"],
  ["输入","shū rù","to input"],
  ["属于","shǔ yú","to belong to"],
  ["数据","shù jù","data"],
  ["数量","shù liàng","quantity"],
  ["数字","shù zì","digit"],
  ["双方","shuāng fāng","both sides"],
  ["水平","shuǐ píng","level"],
  ["睡觉","shuì jiào","to sleep"],
  ["顺便","shùn biàn","conveniently"],
  ["顺利","shùn lì","smoothly"],
  ["说明","shuō míng","to explain"],
  ["思考","sī kǎo","to think"],
  ["思想","sī xiǎng","thought"],
  ["私人","sī rén","private"],
  ["速度","sù dù","speed"],
  ["塑料","sù liào","plastic"],
  ["随便","suí biàn","casual"],
  ["随着","suí zhe","along with"],
  ["损坏","sǔn huài","to damage"],
  ["所以","suǒ yǐ","so"],
  ["所有","suǒ yǒu","all"],
  ["态度","tài du","attitude"],
  ["谈判","tán pàn","negotiation"],
  ["坦白","tǎn bái","frank"],
  ["探望","tàn wàng","to visit"],
  ["讨论","tǎo lùn","to discuss"],
  ["特别","tè bié","special"],
  ["特点","tè diǎn","characteristic"],
  ["提高","tí gāo","to improve"],
  ["提供","tí gōng","to provide"],
  ["提前","tí qián","in advance"],
  ["题目","tí mù","title"],
  ["体会","tǐ huì","to realize"],
  ["体现","tǐ xiàn","to embody"],
  ["体育","tǐ yù","sports"],
  ["天然","tiān rán","natural"],
  ["条件","tiáo jiàn","condition"],
  ["调整","tiáo zhěng","to adjust"],
  ["挑战","tiǎo zhàn","challenge"],
  ["讨论","tǎo lùn","to discuss"],
  ["听说","tīng shuō","it is said"],
  ["停止","tíng zhǐ","to stop"],
  ["通常","tōng cháng","usually"],
  ["通过","tōng guò","to pass through"],
  ["通信","tōng xìn","communication"],
  ["通知","tōng zhī","to notify"],
  ["同时","tóng shí","simultaneously"],
  ["同事","tóng shì","colleague"],
  ["同意","tóng yì","to agree"],
  ["统一","tǒng yī","unified"],
  ["痛苦","tòng kǔ","painful"],
  ["投入","tóu rù","to invest"],
  ["突然","tū rán","suddenly"],
  ["图书馆","tú shū guǎn","library"],
  ["土地","tǔ dì","land"],
  ["推动","tuī dòng","to push forward"],
  ["推广","tuī guǎng","to popularize"],
  ["推荐","tuī jiàn","to recommend"],
  ["退出","tuì chū","to withdraw"],
  ["退休","tuì xiū","to retire"],
  ["完成","wán chéng","to complete"],
  ["完善","wán shàn","perfect"],
  ["完全","wán quán","completely"],
  ["网络","wǎng luò","internet"],
  ["往往","wǎng wǎng","often"],
  ["忘记","wàng jì","to forget"],
  ["危险","wēi xiǎn","danger"],
  ["微笑","wēi xiào","smile"],
  ["围绕","wéi rào","to surround"],
  ["违反","wéi fǎn","to violate"],
  ["维护","wéi hù","to maintain"],
  ["伟大","wěi dà","great"],
  ["未必","wèi bì","not necessarily"],
  ["未来","wèi lái","future"],
  ["位置","wèi zhì","position"],
  ["温暖","wēn nuǎn","warm"],
  ["文化","wén huà","culture"],
  ["文件","wén jiàn","document"],
  ["文明","wén míng","civilization"],
  ["文学","wén xué","literature"],
  ["文章","wén zhāng","article"],
  ["问题","wèn tí","problem"],
  ["污染","wū rǎn","pollution"],
  ["无比","wú bǐ","incomparable"],
  ["无法","wú fǎ","unable"],
  ["无论","wú lùn","no matter"],
  ["无奈","wú nài","helpless"],
  ["无情","wú qíng","merciless"],
  ["无数","wú shù","countless"],
  ["武器","wǔ qì","weapon"],
  ["武术","wǔ shù","martial arts"],
  ["物理","wù lǐ","physics"],
  ["物质","wù zhì","matter"],
  ["误会","wù huì","misunderstanding"],
  ["吸收","xī shōu","to absorb"],
  ["希望","xī wàng","to hope"],
  ["习惯","xí guàn","habit"],
  ["细节","xì jié","detail"],
  ["系统","xì tǒng","system"],
  ["下午","xià wǔ","afternoon"],
  ["先后","xiān hòu","one after another"],
  ["现象","xiàn xiàng","phenomenon"],
  ["现在","xiàn zài","now"],
  ["限制","xiàn zhì","to limit"],
  ["相当","xiāng dāng","quite"],
  ["相反","xiāng fǎn","opposite"],
  ["相关","xiāng guān","relevant"],
  ["相似","xiāng sì","similar"],
  ["相同","xiāng tóng","identical"],
  ["相信","xiāng xìn","to believe"],
  ["详细","xiáng xì","detailed"],
  ["想法","xiǎng fǎ","idea"],
  ["想象","xiǎng xiàng","to imagine"],
  ["消费","xiāo fèi","to consume"],
  ["消失","xiāo shī","to disappear"],
  ["消息","xiāo xi","news"],
  ["销售","xiāo shòu","to sell"],
  ["小说","xiǎo shuō","novel"],
  ["效果","xiào guǒ","effect"],
  ["效率","xiào lǜ","efficiency"],
  ["校长","xiào zhǎng","principal"],
  ["校园","xiào yuán","campus"],
  ["协商","xié shāng","to negotiate"],
  ["写作","xiě zuò","writing"],
  ["心理","xīn lǐ","psychology"],
  ["心情","xīn qíng","mood"],
  ["辛苦","xīn kǔ","hard (work)"],
  ["新年","xīn nián","new year"],
  ["新鲜","xīn xiān","fresh"],
  ["信任","xìn rèn","to trust"],
  ["信息","xìn xī","information"],
  ["信心","xìn xīn","confidence"],
  ["行动","xíng dòng","action"],
  ["形成","xíng chéng","to form"],
  ["形势","xíng shì","situation"],
  ["形象","xíng xiàng","image"],
  ["形状","xíng zhuàng","shape"],
  ["兴趣","xìng qù","interest"],
  ["幸福","xìng fú","happiness"],
  ["性别","xìng bié","gender"],
  ["性质","xìng zhì","nature"],
  ["休想","xiū xiǎng","don't think"],
  ["休息","xiū xi","to rest"],
  ["修改","xiū gǎi","to modify"],
  ["修理","xiū lǐ","to repair"],
  ["需要","xū yào","to need"],
  ["许多","xǔ duō","many"],
  ["宣传","xuān chuán","to promote"],
  ["选择","xuǎn zé","to choose"],
  ["学术","xué shù","academic"],
  ["学习","xué xí","to study"],
  ["学校","xué xiào","school"],
  ["迅速","xùn sù","rapid"],
  ["压力","yā lì","pressure"],
  ["严重","yán zhòng","serious"],
  ["研究","yán jiū","to research"],
  ["颜色","yán sè","color"],
  ["演出","yǎn chū","performance"],
  ["要求","yāo qiú","to demand"],
  ["邀请","yāo qǐng","to invite"],
  ["也许","yě xǔ","perhaps"],
  ["业务","yè wù","business"],
  ["夜晚","yè wǎn","night"],
  ["一切","yī qiè","everything"],
  ["一样","yī yàng","same"],
  ["医疗","yī liáo","medical"],
  ["医生","yī shēng","doctor"],
  ["医院","yī yuàn","hospital"],
  ["依靠","yī kào","to rely on"],
  ["依然","yī rán","still"],
  ["疑问","yí wèn","doubt"],
  ["已经","yǐ jīng","already"],
  ["以后","yǐ hòu","after"],
  ["以前","yǐ qián","before"],
  ["意见","yì jiàn","opinion"],
  ["意识","yì shí","consciousness"],
  ["意思","yì si","meaning"],
  ["意外","yì wài","accident"],
  ["因此","yīn cǐ","therefore"],
  ["因为","yīn wèi","because"],
  ["音乐","yīn yuè","music"],
  ["银行","yín háng","bank"],
  ["印象","yìn xiàng","impression"],
  ["应该","yīng gāi","should"],
  ["影响","yǐng xiǎng","influence"],
  ["应用","yìng yòng","to apply"],
  ["拥抱","yōng bào","to hug"],
  ["拥有","yōng yǒu","to possess"],
  ["永远","yǒng yuǎn","forever"],
  ["勇敢","yǒng gǎn","brave"],
  ["优点","yōu diǎn","advantage"],
  "["优先","yōu xiān","priority"],
  ["尤其","yóu qí","especially"],
  ["由于","yóu yú","due to"],
  ["邮电","yóu diàn","postal & telecom"],
  ["犹豫","yóu yù","hesitant"],
  ["游戏","yóu xì","game"],
  ["友好","yǒu hǎo","friendly"],
  ["有关","yǒu guān","related"],
  ["有利","yǒu lì","favorable"],
  ["有时","yǒu shí","sometimes"],
  ["有效","yǒu xiào","effective"],
  ["有趣","yǒu qù","interesting"],
  ["有限","yǒu xiàn","limited"],
  ["有些","yǒu xiē","some"],
  ["幼稚","yòu zhì","childish"],
  ["于是","yú shì","thereupon"],
  ["娱乐","yú lè","entertainment"],
  ["愉快","yú kuài","pleasant"],
  ["余地","yú dì","leeway"],
  ["宇宙","yǔ zhòu","universe"],
  ["语言","yǔ yán","language"],
  ["遇到","yù dào","to encounter"],
  ["预习","yù xí","to preview"],
  ["元旦","yuán dàn","New Year's Day"],
  ["原来","yuán lái","originally"],
  ["原因","yuán yīn","cause"],
  ["原则","yuán zé","principle"],
  ["阅读","yuè dú","to read"],
  ["允许","yǔn xǔ","to permit"],
  ["运动","yùn dòng","sports"],
  ["运气","yùn qi","luck"],
  ["再不","zài bù","otherwise"],
  ["再说","zài shuō","besides"],
  ["暂时","zàn shí","temporary"],
  ["赞赏","zàn shǎng","to admire"],
  ["早晨","zǎo chén","morning"],
  ["造成","zào chéng","to cause"],
  ["责任","zé rèn","responsibility"],
  ["增加","zēng jiā","to increase"],
  ["增长","zēng zhǎng","to grow"],
  ["债务","zhài wù","debt"],
  ["展览","zhǎn lǎn","exhibition"],
  ["展开","zhǎn kāi","to unfold"],
  ["战斗","zhàn dòu","battle"],
  ["战争","zhàn zhēng","war"],
  ["掌握","zhǎng wò","to master"],
  ["招待","zhāo dài","to entertain"],
  ["招聘","zhāo pìn","to recruit"],
  ["召开","zhào kāi","to convene"],
  ["照顾","zhào gù","to take care of"],
  ["照片","zhào piàn","photo"],
  ["哲学","zhé xué","philosophy"],
  ["这些","zhè xiē","these"],
  ["针对","zhēn duì","to target"],
  ["诊断","zhěn duàn","diagnosis"],
  ["真的","zhēn de","really"],
  ["争论","zhēng lùn","argument"],
  ["整理","zhěng lǐ","to tidy"],
  ["正常","zhèng cháng","normal"],
  ["正好","zhèng hǎo","just right"],
  ["正式","zhèng shì","formal"],
  ["政策","zhèng cè","policy"],
  ["政府","zhèng fǔ","government"],
  ["政治","zhèng zhì","politics"],
  ["支持","zhī chí","to support"],
  ["知道","zhī dào","to know"],
  ["知识","zhī shi","knowledge"],
  ["执行","zhí xíng","to execute"],
  ["直接","zhí jiē","direct"],
  ["职业","zhí yè","occupation"],
  ["植物","zhí wù","plant"],
  ["只要","zhǐ yào","as long as"],
  ["指导","zhǐ dǎo","to guide"],
  ["指挥","zhǐ huī","to command"],
  ["质量","zhì liàng","quality"],
  ["至少","zhì shǎo","at least"],
  ["至于","zhì yú","as for"],
  ["制订","zhì dìng","to formulate"],
  ["制造","zhì zào","to manufacture"],
  ["中华民族","zhōng huá mín zú","Chinese nation"],
  ["中间","zhōng jiān","middle"],
  ["中小企业","zhōng xiǎo qǐ yè","SME"],
  ["中心","zhōng xīn","center"],
  ["中央","zhōng yāng","central"],
  ["忠诚","zhōng chéng","loyal"],
  ["终于","zhōng yú","finally"],
  ["种类","zhǒng lèi","kind"],
  ["重大","zhòng dà","significant"],
  ["重点","zhòng diǎn","key point"],
  ["重量","zhòng liàng","weight"],
  ["周到","zhōu dào","thorough"],
  ["周围","zhōu wéi","surroundings"],
  ["主要","zhǔ yào","main"],
  ["主张","zhǔ zhāng","to advocate"],
  ["住房","zhù fáng","housing"],
  ["著名","zhù míng","famous"],
  ["抓紧","zhuā jǐn","to seize"],
  ["专家","zhuān jiā","expert"],
  ["专业","zhuān yè","major"],
  ["转变","zhuǎn biàn","to transform"],
  ["转移","zhuǎn yí","to transfer"],
  ["装饰","zhuāng shì","decoration"],
  ["追求","zhuī qiú","to pursue"],
  ["准确","zhǔn què","accurate"],
  ["准时","zhǔn shí","on time"],
  ["资格","zī gé","qualification"],
  ["资金","zī jīn","funds"],
  ["资料","zī liào","material"],
  ["资源","zī yuán","resource"],
  ["自动","zì dòng","automatic"],
  ["自己","zì jǐ","self"],
  ["自然","zì rán","nature"],
  ["自信","zì xìn","confident"],
  ["自由","zì yóu","freedom"],
  ["自愿","zì yuàn","voluntary"],
  ["综合","zōng hé","comprehensive"],
  ["总结","zǒng jié","to summarize"],
  ["总理","zǒng lǐ","premier"],
  ["总统","zǒng tǒng","president"],
  ["走向","zǒu xiàng","to tend"],
  ["祖国","zǔ guó","motherland"],
  ["阻止","zǔ zhǐ","to prevent"],
  ["组织","zǔ zhī","to organize"],
  ["最初","zuì chū","initial"],
  ["最好","zuì hǎo","best"],
  ["最后","zuì hòu","final"],
  ["尊敬","zūn jìng","to respect"],
  ["遵守","zūn shǒu","to obey"],
  ["作品","zuò pǐn","work (art)"],
  ["作为","zuò wéi","to act as"],
  ["作文","zuò wén","composition"],
  ["作业","zuò yè","homework"],
  ["作用","zuò yòng","function"],
  ["作者","zuò zhě","author"],
  ["做人","zuò rén","to conduct oneself"],
  ["做作业","zuò zuò yè","to do homework"],
];

async function tryFetch(url) {
  try {
    const resp = await fetch(url);
    if (!resp.ok) return null;
    return await resp.text();
  } catch {
    return null;
  }
}

async function main() {
  // Try URLs in order
  for (const url of URLs) {
    const text = await tryFetch(url);
    if (text) {
      const lines = text.trim().split('\n');
      const entries = [];
      for (const line of lines) {
        const parts = line.trim().split(/\s+/);
        if (parts.length < 3) continue;
        entries.push({
          english: parts.slice(2).join(' '),
          hanzi: parts[0],
          pinyin: parts[1],
          difficulty: 'simple',
          category: 'HSK 5'
        });
      }
      if (entries.length > 100) {
        writeFileSync(outputPath, JSON.stringify(entries, null, 2));
        console.log(`✅ Generated HSK 5 vocabulary: ${entries.length} words from ${url}`);
        return;
      }
    }
  }

  // Fallback: write the embedded list
  const entries = FALLBACK_WORDS.map(([hanzi, pinyin, english]) => ({
    english,
    hanzi,
    pinyin,
    difficulty: 'simple',
    category: 'HSK 5'
  }));
  writeFileSync(outputPath, JSON.stringify(entries, null, 2));
  console.log(`✅ Generated HSK 5 vocabulary: ${entries.length} words (fallback)`);
}

main();